sudo: required

language: cpp

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - . ./DiligentCore/BuildTools/Scripts/travis/before_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - CONFIG=Debug
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Debug
      - IOS=false
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Debug
      - IOS=true
  - os: linux
    compiler: gcc
    env:
      - CONFIG=Release
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=false
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=true

script:

  - cd ./DiligentCore/BuildTools/FormatValidation
  - . ../Scripts/travis/validate_format.sh
  - cd ../../../DiligentTools/BuildTools/FormatValidation
  - . ../../../DiligentCore/BuildTools/Scripts/travis/validate_format.sh
  - cd ../../../DiligentFX/BuildTools/FormatValidation
  - . ../../../DiligentCore/BuildTools/Scripts/travis/validate_format.sh
  - cd ../../../DiligentSamples/BuildTools/FormatValidation
  - . ../../../DiligentCore/BuildTools/Scripts/travis/validate_format.sh
  - cd ../../../
  - . ./DiligentCore/BuildTools/Scripts/travis/build.sh "-DDILIGENT_ENABLE_TESTS=TRUE"
  - cd ../DiligentCore/Tests/DiligentCoreAPITest/assets
  - . ../../../BuildTools/Scripts/travis/run_tests.sh ../../../../build/DiligentCore
