name: MacOS/iOS/tvOS build

on: [push, pull_request]

jobs:
  precheks:
    runs-on: macos-14
    name: MacOS -> Pre-Checks

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: true # only need direct submodules

    - name: DiligentCore format validation
      working-directory: ${{github.workspace}}/DiligentCore/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_mac.sh

    - name: DiligentTools format validation
      working-directory: ${{github.workspace}}/DiligentTools/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_mac.sh

    - name: DiligentFX format validation
      working-directory: ${{github.workspace}}/DiligentFX/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_mac.sh

    - name: DiligentSamples format validation
      working-directory: ${{github.workspace}}/DiligentSamples/BuildTools/FormatValidation
      shell: bash
      run: ./validate_format_mac.sh


  build:
    needs:   precheks
    runs-on: macos-14

    strategy:
      matrix:
        platform:   ["MacOS", "iOS", "tvOS"]
        build_type: ["Debug", "Release"]

        exclude:
          # Exclude tvOS-Release
          - platform:   "tvOS"
            build_type: "Release"

        include:
          - platform:   "MacOS"
            build_type: "Debug"
            cmake_args: "-DDILIGENT_BUILD_TESTS=ON"

          - platform:   "MacOS"
            build_type: "Release"
            # For some reason AVX2 causes invalid instruction exception on CI in CoreTest, so disable it
            cmake_args: "-DDILIGENT_BUILD_CORE_TESTS=ON -DDILIGENT_BUILD_TOOLS_TESTS=ON -DDILIGENT_CLANG_RELEASE_COMPILE_OPTIONS=\"\""

          - platform:  "iOS"
            cmake_args: ""

          - platform:   "tvOS"
            cmake_args: ""

    name: MacOS -> ${{ matrix.platform }}-${{ matrix.build_type }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up build environment
      if: success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform: ${{ matrix.platform }}

    - name: Configure CMake
      if: success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v1

    - name: DiligentCoreTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-core-tests@v1

    - name: DiligentToolsTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-tools-tests@v1

    - name: HLSL2GLSLConverterTest
      if:   ${{ success() && matrix.platform == 'MacOS' }}
      uses: DiligentGraphics/github-action/run-hlsl2glsl-converter-test@v1
